In [37]:
import numpy as np

In [38]:
np.__version__

'1.20.3'

In [39]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [40]:
print(a)

[1 2 3 4 5 6 7]


In [41]:
b = list( (1,2,3,4))

In [42]:
b

[1, 2, 3, 4]

In [43]:
a.dtype

dtype('int32')

In [44]:
b.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [45]:
a.ndim

1

In [46]:
a.shape

(7,)

In [47]:
a.itemsize

4

In [48]:
a.tolist()

[1, 2, 3, 4, 5, 6, 7]

In [49]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
print(a)

[1 2 3 4 5 6 7]


In [51]:
c = a.tolist()
c

[1, 2, 3, 4, 5, 6, 7]

In [52]:
c

[1, 2, 3, 4, 5, 6, 7]

In [53]:
d = np.array([1,2,3])

In [54]:
d

array([1, 2, 3])

In [55]:
print(d)

[1 2 3]


In [57]:
f=np.array([1,2,3])

In [58]:
f

array([1, 2, 3])

In [59]:
print(f)

[1 2 3]


In [61]:
d is f

False

In [66]:
e = np.asarray(d)

In [67]:
e is d

True

In [68]:
e

array([1, 2, 3])

In [69]:
g = e.copy()
g

array([1, 2, 3])

In [70]:
g is e

False

In [71]:
g is d

False

In [90]:
import pandas as pd

In [92]:
s = pd.Series([1,2,3,4,5,6,7], index=list('abcdefg'))
s

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [93]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

In [94]:
s.values

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [95]:
s.shape

(7,)

In [96]:
s.ndim

1

In [97]:
s.size

7

In [98]:
s['g']

7

In [99]:
s[-1]

7

In [100]:
s[1:5]

b    2
c    3
d    4
e    5
dtype: int64

In [101]:
s["b":"e"]

b    2
c    3
d    4
e    5
dtype: int64

In [105]:
df = pd.DataFrame([[1,2,3,4],[5,6,7,8]], index = list('ab'), columns=list('abcd'))
df

a  b  c  d
a  1  2  3  4
b  5  6  7  8

In [106]:
df.index

Index(['a', 'b'], dtype='object')

In [107]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [108]:
df.shape

(2, 4)

In [109]:
df.ndim

2

In [110]:
df.size

8