In [16]:
import numpy as np

In [17]:
my_list = [0,1,2,3,4,5,6,7,8,9,10]
nparr = np.array(my_list)
print(nparr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [18]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
nparr = np.arange(0,11)

In [20]:
print(nparr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [21]:
nparr_add = nparr + nparr

In [22]:
nparr_add

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
print(nparr_add)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [24]:
nparr_sub = nparr - nparr

In [26]:
print(nparr_sub)

[0 0 0 0 0 0 0 0 0 0 0]


In [27]:
nparr_esc = nparr * 10
print(nparr_esc)

[  0  10  20  30  40  50  60  70  80  90 100]


In [30]:
nparr_one_div = 1/nparr
print(nparr_one_div)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]


C:\Users\Alvin\AppData\Local\Temp/ipykernel_7532/624558858.py:1: RuntimeWarning: divide by zero encountered in true_divide
  nparr_one_div = 1/nparr


In [33]:
nparr_max = nparr.max(nparr)
print(nparr_max)

TypeError: only integer scalar arrays can be converted to a scalar index